services:

  api:

    build:
      context: ./backend

    container_name: novel-api

    ports:
      - "${APP_PORT}:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app

    restart: unless-stopped