name: novel-ai

services:

  backend:
    build:
      context: D:\AI\novel-ai\backend
      dockerfile: Dockerfile

    container_name: novelforge-backend

    environment:
      API_VERSION: v1
      APP_NAME: NovelForge
      DEBUG: "true"
      QWEN_BASE_URL: http://ollama:11434
      QWEN_MODEL: qwen3:8b
      environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_EMBEDDING_MODEL: qwen3-embedding:0.6b
      OLLAMA_EMBEDDING_DIMENSION: "1024"
      FAISS_INDEX_DIR: /app/data/vector_db

    ports:
      - "18080:8000"

    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - ollama

    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest

    container_name: novelforge-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

    restart: unless-stopped

volumes:
  ollama_data: